### ISSUE TITLE
[BUG] Font doesn't support all Greek characters

### ISSUE THREAD

**Issue by VasilisKos** [tomc128/noterly#16]
Unfortunately, the text font of the app has an issue with Greek characters, and specifically the accentuation symbols and the capital letter "Σ", which appears as "C". I attach a screenshot to see what I mean. 
Can you please change the font to a compatible one? It's very important.

![Screenshot_20230822-104359-picsay](https://github.com/tomc128/noterly/assets/12777771/f8a02f21-e2f7-405c-9c12-93ce649d1aa4)

**Comment by tomc128** [comment]
Fixed in 716955b, will be included in the next release!
