### ISSUE TITLE
[BUG] The bottom navigation bar shows 'archive' in both tabs

### ISSUE THREAD

**Issue by ProficientTroll** [tomc128/noterly#30]
**Describe the bug**
The bottom navigation bar on the app shows archive in both tabs 

**To Reproduce**
1. Open the app
2. Bottom Navigation bar shows archive in both

**Expected behavior**
One tab should show reminders, other should show archive

**Version (please complete the following information):**
 - Device: OnePlus 7T
 - Android version: 14
 - Noterly version : 1.4.3-beta.1 (localisation-v2)

Screenshot:
![Screenshot_20240128-090352_Noterly](https://github.com/tomc128/noterly/assets/157570075/fc335140-9353-434a-8994-d2ccd3317acb)

**Comment by tomc128** [comment]
Thanks for pointing this out. This will be fixed in the next beta release :)
